spring.application.name=jogo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/jogo
spring.datasource.username=root
spring.datasource.password=